### ISSUE TITLE
VP9 output is invalid

### ISSUE THREAD

**Issue by johnluther** [OpenVisualCloud/SVT-VP9#27]
I tried a basic VP9 encode w/ ffmpeg. Here is my command:

`ffmpeg -i 30sec.mp4 -c:v libsvt_vp9 -rc 1 -b:v 1M -r 30 -preset 8 -an -y test.webm`

WebM output file: https://storage.googleapis.com/jluther/test_8.webm
Also an IVF here: https://storage.googleapis.com/jluther/test.ivf

I tried a number of different input files, got the same results. Output container also doesn't seem to matter, I got the same result with .webm as well as .ivf.

When I play the output in VLC, frames are blocky and playback is choppy, as if it is only decoding interframes.

I tried to get info about the keyframes using ffprobe and got this:

```
[vp9 @ 0x55aff4dcc880] Invalid compressed header size
    Last message repeated 50 times
[vp9 @ 0x55aff4dcc880] Marker bit was set
    Last message repeated 17 times
[vp9 @ 0x55aff4dcc880] Invalid compressed header size
```

I had to apply the MAX_CACHE 32 change in #2 to get the encoder to work w/o errors. Otherwise I followed all the build instructions exactly.

I am running a small Google Cloud Linux instance to get an idea of performance on non-scalable Xeons. Here is the cpuinfo:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:              3
CPU MHz:               2000.164
BogoMIPS:              4000.32
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              56320K
NUMA node0 CPU(s):     0,1
Flags:   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
 mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology
 nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes
 xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb
 stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f
 avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec
 xgetbv1 xsaves arat arch_capabilities
```

Thanks in advance for any assistance!

**Comment by tianjunwork** [comment]
Hi @jsunintel Could you help with this issue?

**Comment by jsunintel** [comment]
> 
> 
> I tried a basic VP9 encode w/ ffmpeg. Here is my command:
> 
> `ffmpeg -i 30sec.mp4 -c:v libsvt_vp9 -rc 1 -b:v 1M -r 30 -preset 8 -an -y test.webm`
> 
> WebM output file: https://storage.googleapis.com/jluther/test_8.webm
> Also an IVF here: https://storage.googleapis.com/jluther/test.ivf
> 
> I tried a number of different input files, got the same results. Output container also doesn't seem to matter, I got the same result with .webm as well as .ivf.
> 
> When I play the output in VLC, frames are blocky and playback is choppy, as if it is only decoding interframes.
> 
> I tried to get info about the keyframes using ffprobe and got this:
> 
> ```
> [vp9 @ 0x55aff4dcc880] Invalid compressed header size
>     Last message repeated 50 times
> [vp9 @ 0x55aff4dcc880] Marker bit was set
>     Last message repeated 17 times
> [vp9 @ 0x55aff4dcc880] Invalid compressed header size
> ```
> 
> I had to apply the MAX_CACHE 32 change in #2 to get the encoder to work w/o errors. Otherwise I followed all the build instructions exactly.
> 
> I am running a small Google Cloud Linux instance to get an idea of performance on non-scalable Xeons. Here is the cpuinfo:
> 
> ```
> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                2
> On-line CPU(s) list:   0,1
> Thread(s) per core:    2
> Core(s) per socket:    1
> Socket(s):             1
> NUMA node(s):          1
> Vendor ID:             GenuineIntel
> CPU family:            6
> Model:                 85
> Model name:            Intel(R) Xeon(R) CPU @ 2.00GHz
> Stepping:              3
> CPU MHz:               2000.164
> BogoMIPS:              4000.32
> Hypervisor vendor:     KVM
> Virtualization type:   full
> L1d cache:             32K
> L1i cache:             32K
> L2 cache:              256K
> L3 cache:              56320K
> NUMA node0 CPU(s):     0,1
> Flags:   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
>  mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology
>  nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes
>  xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb
>  stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f
>  avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec
>  xgetbv1 xsaves arat arch_capabilities
> ```
> 
> Thanks in advance for any assistance!

VLC by default doesn't support VP9 decoding. Could you please give me VLC setup steps to view a VP9 clip by VLC?

**Comment by johnluther** [comment]
Thanks, @jsunintel. Version 2.1.1 and later of VLC support VP9 playback in WebM container (see https://www.videolan.org/developers/vlc-branch/NEWS).

I also tried the output in Chrome 73 for Mac, it didn't play there, either.

**Comment by jsunintel** [comment]
Found this issue's root cause: ffmpeg always does a filtering process after SVT VP9 lib outputs a packet of coded data, in which it will check the coded data, get its type (invisible or super frame), and save the coded data to cache if it's an invisible frame or merge the cached frames' data with the current frame data if the current is a super and write them all to the output stream. However, SVT VP9 doesn't need this process and the merging is done inside the lib. Applying superframe merging to the already merged coded data causes all kinds of unexpected behaviors.

I removed it as an experiment, but we need to work out a final solution. Which one, app or lib shall do the merging? If app should do it and the way how ffmpeg is handling this is correct, lib developers need to remove it from lib and let the lib callers do it.

@@ -94,10 +118,11 @@ static int ivf_check_bitstream(struct AVFormatContext *s, const AVPacket *pkt)
 {
     int ret = 1;
     AVStream *st = s->streams[pkt->stream_index];
-
+#if 0
     if (st->codecpar->codec_id == AV_CODEC_ID_VP9)
         ret = ff_stream_add_bitstream_filter(st, "vp9_superframe", NULL);
-    else if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
+#endif
+    if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
         ret = ff_stream_add_bitstream_filter(st, "av1_metadata", "td=insert");

     return ret;

And there is another issue: SVT VP9 test app is doing some kind of quirk on making the ivf frame headers while there is no such thing in ffmpeg. I hard coded it to ffmpeg, and I know it's urgly, but with the 2 parts of code changed, it works good and the output bitstream gets successfully decoded. Is that 4 frame headers writing a temp workaround or final? It will be very hard to get such thing accepted by the ffmpeg community. 

--- a/libavcodec/libsvt_vp9.c
+++ b/libavcodec/libsvt_vp9.c
@@ -354,6 +354,9 @@ static int eb_receive_packet(AVCodecContext *avctx, AVPacket *pkt)
     if (headerPtr->pic_type == EB_NON_REF_PICTURE)
         pkt->flags |= AV_PKT_FLAG_DISPOSABLE;

+    if (headerPtr->flags & EB_BUFFERFLAG_SHOW_EXT)
+        pkt->flags |= 0x1000;
+
     ret = (headerPtr->flags & EB_BUFFERFLAG_EOS) ? AVERROR_EOF : 0;

     eb_vp9_svt_release_out_buffer(&headerPtr);

diff --git a/libavformat/ivfenc.c b/libavformat/ivfenc.c
index adf7211..9a77450 100644
--- a/libavformat/ivfenc.c
+++ b/libavformat/ivfenc.c
@@ -63,9 +63,33 @@ static int ivf_write_packet(AVFormatContext *s, AVPacket *pkt)
     AVIOContext *pb = s->pb;
     IVFEncContext *ctx = s->priv_data;

-    avio_wl32(pb, pkt->size);
-    avio_wl64(pb, pkt->pts);
-    avio_write(pb, pkt->data, pkt->size);
+    if (pkt->flags & 0x1000) {
+        avio_wl32(pb, pkt->size - 4);
+        avio_wl64(pb, pkt->pts);
+        avio_write(pb, pkt->data, pkt->size - 4);
+
+        avio_wl32(pb, 1);
+        avio_wl64(pb, pkt->pts - 2);
+        avio_write(pb, pkt->data + pkt->size - 4, 1);
+
+        avio_wl32(pb, 1);
+        avio_wl64(pb, pkt->pts - 1);
+        avio_write(pb, pkt->data + pkt->size - 3, 1);
+
+        avio_wl32(pb, 1);
+        avio_wl64(pb, pkt->pts);
+        avio_write(pb, pkt->data + pkt->size - 2, 1);
+
+        avio_wl32(pb, 1);
+        avio_wl64(pb, pkt->pts + 1);
+        avio_write(pb, pkt->data + pkt->size - 1, 1);
+    }
+    else {
+        avio_wl32(pb, pkt->size);
+        avio_wl64(pb, pkt->pts);
+        avio_write(pb, pkt->data, pkt->size);
+    }

I was trying the ivf mux, but it's similar to webp. To reproduce my results, please apple the above code changes and run "ffmpeg -s 1920x1080 -f rawvideo -i /work/clips/matrix_1920x1080_250i.yuv -rc 0 -c:v libsvt_vp9 -vframes 250 -g 32 -tune 1 -qp 45 -y rc0.ivf", then "ffmpeg -i rc0.ivf -y rc0.yuv", then play the rc0.yuv, which is of i420 format.

**Comment by 1480c1** [comment]
@jsunintel you can block off your logs using '```' to prevent github from formatting your logs and diffs using markdown syntax <https://help.github.com/en/articles/creating-and-highlighting-code-blocks> 
that way your diffs and logs won't look so weird.

PS: you can use " ``` diff " to specifically mark something to be highlighted like a diff

**Comment by 1480c1** [comment]
Not like that

**Comment by jsunintel** [comment]
> 
> 
> Only put the triple back tick in the beginning
> newline
> code
> and then triple at the end
> 
> ```diff
> @@ -94,10 +118,11 @@ static int ivf_check_bitstream(struct AVFormatContext *s, const AVPacket *pkt)
> {
> int ret = 1;
> AVStream *st = s->streams[pkt->stream_index];
> 
> +#if 0
> if (st->codecpar->codec_id == AV_CODEC_ID_VP9)
> ret = ff_stream_add_bitstream_filter(st, "vp9_superframe", NULL);
> 
>     else if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
> +#endif
> 
>     if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
>     ret = ff_stream_add_bitstream_filter(st, "av1_metadata", "td=insert");
> 
>     return ret;
> 
> @@ -94,10 +118,11 @@ static int ivf_check_bitstream(struct AVFormatContext *s, const AVPacket *pkt)
>  {
>  int ret = 1;
>  AVStream *st = s->streams[pkt->stream_index];
> +#if 0
>  if (st->codecpar->codec_id == AV_CODEC_ID_VP9)
>  ret = ff_stream_add_bitstream_filter(st, "vp9_superframe", NULL);
> - else if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
> +#endif
> + if (st->codecpar->codec_id == AV_CODEC_ID_AV1)
>  ret = ff_stream_add_bitstream_filter(st, "av1_metadata", "td=insert");
> ```

It is driving me crazy...
Thanks for the helps, and I just made it in a commit: https://github.com/jsunintel/SVT-VP9/commit/9f41ffb9ee5caccdf501e8d5261f7ff99a47c576

**Comment by 1480c1** [comment]
That's one way to do it

**Comment by jsunintel** [comment]
I updated the ffmpeg plugin patches and made vp9 with ivf mux work:

ffmpeg -s 1920x1080 -f rawvideo -i /work/clips/matrix_1920x1080_250i.yuv -rc 0 -c:v libsvt_vp9 -vframes 250 -g 32 -tune 1 -qp 45 -y rc0.ivf
ffplay rc0.ivf

**Comment by johnluther** [comment]
@jsunintel I tested the new patch my .ivf output plays in ffplay and VLC. Thanks very much!
