### ISSUE TITLE
Even with commit ce24589 I still get [vp9 @ 0x7fa7d0806200] Invalid compressed header size when playing in FFPLAY

### ISSUE THREAD

**Issue by colleenkhenry** [OpenVisualCloud/SVT-VP9#29]
Is there something I should do other than using the most recent master and follow the ffmpeg plugin directions?

**Comment by tianjunwork** [comment]
Hi @colleenkhenry, based on the discussion in https://github.com/OpenVisualCloud/SVT-VP9/issues/27, at least it works with ivf file. Could you use the same command line and try it again?

**Comment by tianjunwork** [comment]
Hi @colleenkhenry, I use below command line from https://github.com/OpenVisualCloud/SVT-VP9/issues/27. It works for me. Please send us your command line which doesn't work. Thx.
ffmpeg -s 1920x1080 -f rawvideo -i /work/clips/matrix_1920x1080_250i.yuv -rc 0 -c:v libsvt_vp9 -vframes 250 -g 32 -tune 1 -qp 45 -y rc0.ivf
ffplay rc0.ivf

**Comment by colleenkhenry** [comment]
Here ou go. 

I'll try yours now. 

ffmpeg -i ~/Videos/ToS-4k-1920.mov -pix_fmt yuv420p -s 960x400 -c:v libsvt_vp9 -preset 8 -an test8.ivf

**Comment by colleenkhenry** [comment]
Your command works for me :).  Whats the difference?

**Comment by colleenkhenry** [comment]
One thing thats weird is when I change it to -g 60, I get this error. 64 works. It seems it has to be divisible in a certain way for the GOP size?

disp_order_continuity_count Error2 POC:63B time=00:00:01.53 b

Do you guys have a slack channel you hang out in?

**Comment by tianjunwork** [comment]
1. MOV issue:
"Invalid compressed header size" seems only shows up for MOV input. I tried with yuv and mp4. It works fine with your command.
I didn't observe the difference between -g 60 and -g 64. If the input is MOV, both only shows "compressed header size".
The owner of ffmpeg plugin is on vacation. I will ask her to look into MOV issue after.

2. Could you send the command to get this error? "disp_order_continuity_count Error2"

3. We don't use slack yet. All the issues from Github are discussed only here so that others can track. But I also think it is a good idea for collaboration/discussion in depth😄

**Comment by tianjunwork** [comment]
Hi @jsunintel, for mov input, e.g. "ffmpeg -i ~/Videos/ToS-4k-1920.mov -pix_fmt yuv420p -s 960x400 -c:v libsvt_vp9 -preset 8 -an test8.ivf" ffplay shows "Invalid compressed header size" error, could you take a look?

**Comment by colleenkhenry** [comment]
Thanks! I'll get back to you with all this.

**Comment by jsunintel** [comment]
According to your logs, the failure occured when decoding the  oS-4k-1920.mov, but not encoding. 
Can I have your clip file to do more debugging? Also, you could try "ffmpeg -i ~/Videos/ToS-4k-1920.mov -pix_fmt yuv420p -s 960x400 -y test.yuv" to double confirm if it's a decoding issue.
