### ISSUE TITLE
ffmpeg: Video corrupted

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-VP9#70]
Building on SVT-VP9 master (615e4a4) with FFmpeg master (4d980a8ceb) on Ubuntu 19.10

``` bash
git clone https://github.com/OpenVisualCloud/SVT-VP9.git
cd SVT-VP9/Build/linux
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
make -j $(nproc) && sudo make install
cd -
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
curl https://raw.githubusercontent.com/OpenVisualCloud/SVT-VP9/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch | git am
mkdir build && cd build
../configure --enable-libsvtvp9 --enable-static --disable-shared && make -j $(nproc)
youtube-dl -f 137 i1IKnWDecwA -o phoenix.mp4 # 1080p24 fps video only, no audio selected
./ffmpeg -i phoenix.mp4 -c:v libsvt_vp9 phoenix.ivf
```

Original video ~2 seconds in. Played through vlc (Latest 3.0.8 Windows 10)
![vlcsnap-2019-11-07-14h59m40s094](https://user-images.githubusercontent.com/8345542/68422999-43e06b00-016f-11ea-8ff5-d02e84ca11d9.png)

Encoded video ~2 seconds in. Played through vlc (Latest 3.0.8 Windows 10)
![vlcsnap-2019-11-07-14h54m28s388](https://user-images.githubusercontent.com/8345542/68422644-98371b00-016e-11ea-940f-491d7120585c.png)

**Comment by 1480c1** [comment]
[phoenix.zip](https://github.com/OpenVisualCloud/SVT-VP9/files/3821483/phoenix.zip)
First 72 frames of the encoded video. 

Full encoded video is 61% larger than the original

**Comment by intelmark** [comment]
Chris - want to confirm the build steps.  The existing readme (https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/README.md) uses branch 4.1 of ffmpeg:

Also when following instructions, I seemed to hang on this command:
curl https://raw.githubusercontent.com/OpenVisualCloud/SVT-VP9/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch | git am
mkdir build && cd build



Existing readme:
Build and install SVT-VP9
git clone https://github.com/OpenVisualCloud/SVT-VP9
cd SVT-VP9
cd Build && cmake .. && make -j nproc && sudo make install
Apply SVT-VP9 plugin and enable libsvtvp9 to FFmpeg
git clone https://github.com/FFmpeg/FFmpeg ffmpeg
cd ffmpeg
git checkout release/4.1
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
SVT-VP9 alone:
git apply SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
./configure --enable-libsvtvp9
Based on SVT-HEVC & SVT-AV1:
git apply SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
git apply SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
git apply SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-svt-hevc-av1.patch
./configure --enable-libsvthevc --enable-libsvtav1 --enable-libsvtvp9
make -j nproc
Verify
./ffmpeg -i input.mp4 -c:v libsvt_vp9 -rc 1 -b:v 10M -preset 1 -y test.ivf
./ffmpeg -i input.mp4 -vframes 1000 -c:v libsvt_vp9 -y test.mp4

**Comment by tianjunwork** [comment]
Hi Mark, why not git am the local copy of 0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch?

**Comment by 1480c1** [comment]
you can replace `curl https://raw.githubusercontent.com/OpenVisualCloud/SVT-VP9/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch | git am` with `git am <Wherever you have SVT-VP9>/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch`

**Comment by intelmark** [comment]
Any thoughts on not using the 4.1 branch of ffmpeg?

**Comment by 1480c1** [comment]
Main reason why is because I have almost never used any release tars or branches for anything other than testing. Plus, since SVT encoders aren't mainlined, so main compatibility and stability concerns would come from being able to apply it to ffmpeg at any time, and if the corruption happened because of where the patch applied, that would mean that vp9 or ivf output was corrupted on ffmpeg's side.

P.S. 4.1 also has the same issue.

**Comment by tianjunwork** [comment]
Hi @intelmark, I reproduced on 4.1 release branch.

**Comment by intelmark** [comment]
Looks like this issue is independent of ffmpeg as it can be reproduced in the VP9 sample app.

The provided ffmpeg command:
./ffmpeg -i phoenix.mp4 -c:v libsvt_vp9 phoenix.ivf
produced the corrupt bitstream (as reported) and output the following in the ffmpeg log:

SVT [config]: Profile [0]       Level (auto)
SVT [config]: EncoderMode / Tune                                               : 9 / 0
SVT [config]: EncoderBitDepth                                                  : 8
SVT [config]: SourceWidth / SourceHeight                                       : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType    : 24 / 1 / 12 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure         : 3 / 0 / 2
SVT [config]: BRC Mode / QP                                                    : CQP / 32

I thought I should see if I could duplicate the problem using just the sample app with similar parameters and not using ffmpeg.

phoenix.mp4 can be found at \\dcpae-nas.sc.intel.com\dcpae\_Teams\SVT\ffmpeg70\phoenix,mp4

I created a yuv using:
ffmpeg -i phoenix.mp4  phoenix.yuv

Next I created a VP9 file with the sample app:
SVT-VP9/Bin/Release/SvtVp9EncApp -i phoenix.yuv -w 1920 -h 1080 -tune 0 -enc-mode 9  -fps 24 -q 32 -n 200 -b test5.ivf

This produced a valid stream and the encoder showed:

SVT [config]: Profile [0]       Level (auto)
SVT [config]: EncoderMode / Tune                                                : 9 / 0
SVT [config]: EncoderBitDepth                                                   : 8
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 24 / 24
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP                                                     : CQP / 32

I then tried to match the Gop size by adding an intra-period parameter:
SVT-VP9/Bin/Release/SvtVp9EncApp -i phoenix.yuv -w 1920 -h 1080 -tune 0 -enc-mode 9 -intra-period 11 -fps 24 -q 32 -n 200 -b test4.ivf

This produced an invalid stream with similar artifacts to the reported problem and encoder showed (virtually identical to values shown in the ffmpeg output):

SVT [config]: Profile [0]       Level (auto)
SVT [config]: EncoderMode / Tune                                                : 9 / 0
SVT [config]: EncoderBitDepth                                                   : 8
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 24 / 12
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP                                                     : CQP / 45
