### ISSUE TITLE
ffmpeg: Can't encode to webm nor mkv

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-VP9#74]
```bash
git clone https://github.com/FFmpeg/FFmpeg.git --branch=release/4.2 # or 4.1 too
curl "https://raw.githubusercontent.com/OpenVisualCloud/SVT-VP9/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch" | git apply
mkdir build
cd build
../configure --enable-libvorbis --enable-nonfree --enable-gpl  --enable-libopus --enable-libsvtvp9
make -j 10
```

and running `ffmpeg -y -i input.mkv -c:v libsvt_vp9 output.webm` or `ffmpeg -y -i input.mkv -c:v libsvt_vp9 output.mkv` causes
```none
[AVBSFContext @ 0x55f93bb172c0] Too many invisible frames
[AVBSFContext @ 0x55f93bb172c0] Failed to receive packet from filter vp9_superframe for stream 0
```
similar to https://github.com/OpenVisualCloud/SVT-VP9/issues/13

**Comment by Ballevill** [comment]
I confirm there is a bug with webm and mkv

**Comment by tianjunwork** [comment]
Hi @1480c1 @Ballevill, @Austin-Hu is currently looking into this issue. Will keep you updated.

**Comment by tianjunwork** [comment]
FYI, we have a solution to fix this issue. Will submit a PR soon.

**Comment by 1480c1** [comment]
Is it not https://github.com/OpenVisualCloud/SVT-VP9/pull/78?

**Comment by tianjunwork** [comment]
It is not #78. Austin is working on a new PR.

**Comment by Austin-Hu** [comment]
Hi @1480c1 & @Ballevill ,

I tried to revert PR #28 which wouldn't be accepted by ffmpeg community, and to resolve the issue in SVT-VP9 encoder plugin, with PR #78 . But playback of the encoded bit stream has some jitter (repeated frame) issue, which may be due to the incompletely super frame splitting, and needs more investigation in the future.

And according to some suggestions, changing the packetization of SVT-VP9 encoder would be quite a significant effort. So I have to follow the same idea of PR #28 , with PR #79 figured out. And please also test it in your side. Thanks!

**Comment by Austin-Hu** [comment]
Hi @Ballevill ,

Which ffmpeg branch (4.1, 4.2 or master) are you using right now? Because maybe we need to rebase PR #79 per your request. Thanks!

**Comment by Austin-Hu** [comment]
Hi @Ballevill & @1480c1 ,

Due to some implementation changes in the mkv/webm container between ffmpeg v4.2 and master branches, I submitted 2 PRs below:

- PR #80 : Based on ffmpeg [v4.2](https://github.com/FFmpeg/FFmpeg/commit/192d1d34eb3668fa27f433e96036340e1e5077a0) which is SVT-VP9 plugin target, and we will merge it after the reviewing process.
- PR #79 : Based on ffmpeg master [commit](https://github.com/FFmpeg/FFmpeg/commit/e7c04eaf50b4b50f2528ab2c69b76777a1862535), so you can apply the PR without confliction if you're using ffmpeg master branch.

Thanks!

**Comment by 1480c1** [comment]
I can try to test it in a little bit, right now waiting for another ffmpeg build to finish
