### ISSUE TITLE
Incorrect encoded bitstream with some specific resolutions (such as 360x360)

### ISSUE THREAD

**Issue by Austin-Hu** [OpenVisualCloud/SVT-VP9#85]
As found by @1480c1 in PR #83 , the playback of encoded bitstream is incorrect with some specific resolutions (such as 360x360):

./SvtVp9EncApp -i neighbor_360x360_420p.yuv -w 360 -h 360 -b output.vp9

[neighbor_360x360_420p_20frames.zip](https://github.com/OpenVisualCloud/SVT-VP9/files/4150315/neighbor_360x360_420p_20frames.zip)

**Comment by lampcover** [comment]
SvtVp9EncApp.exe -i TearOfSteel_720x540_420P_72Frames.yuv -w 720 -h 480 -fps 24 -b bug.ivf
I can reproduce similar observation of artifacts as of previous comment.

The source can be found at: https://www.dropbox.com/s/fh662emsczlfqkl/TearOfSteel_720x540_420P_72Frames.zip?dl=0

I think its due to the width is not multiple of 32. I tried with 732x480 YUV, it works and without artifacts.
Also, these factors will not resolve artifacts, with width 720:
height/fps (tried various heights/fps)
CBR vs CQP
CBR bitrate
-asm 1 or 0

Also tried to EB_ALIGN_MALLOC for all SDK buffers instead of EB_ALIGN (and replaced EB_CALLOC to EB_ALIGN_MALLOC with memset), doesnt solve the problem as well

I check the output via VLC 3.0.11.
Using FFMPEG to transcode the output with artifacts will give no warning nor error. cmd used:
ffmpeg.exe -i bug.ivf ffmpeg_bug.wmv -loglevel debug

Please let me know if you need more information.
Thanks

**Comment by tianjunwork** [comment]
@lampcover Thank you for doing all the experiments. We are also looking into this issue now. But didn't find the root cause yet.
